version: '3.8'

services:
  voicescenariocoach:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]
    restart: unless-stopped
